#ifndef INKAMATH_CHECK_HPP
#define INKAMATH_CHECK_HPP

#include "inkamath/compile.hpp"
#include "inkamath/interpreter.hpp"
#include "inkamath/number.hpp"

#include <cmath>
#include <cstdio>
#include <optional>
#include <stdexcept>
#include <string>
#include <variant>
#include <vector>

// The oracle (DESIGN.md, next in line): a C program that steps an instance,
// compiled, on the inputs the interpreter gives it, and holds each term to the
// interpreter's, which is exact where the mathematics allows. Inputs are
// replayed rather than computed, so a difference is the step's own.
class CheckC {
public:
    using Value = Matrix<Number>;

    static constexpr int steps = 100;

    // 'unfed' is the instance with its parameters and no input, as
    // ReferenceStack::Unfed makes it.
    static std::string Program(Interpreter<Number>& session, const std::string& instance,
                               const std::string& module, const std::string& source,
                               const Scope<Value>& unfed) {
        const CompileC::Compiled compiled =
            CompileC::Build(session.Definitions(), module, source, unfed.model, &unfed);
        const int         first = compiled.first;
        const std::string index = first == 0 ? "" : std::to_string(first) + " + ";
        std::string       data, stepped, held;
        for (std::size_t k = 0; k < compiled.inputs.size(); ++k) {
            std::vector<std::string> values;
            for (int n = first; n < first + steps; ++n) {
                const Term input = At(session, instance + "." + compiled.inputs[k], n);
                if (!input.error.empty()) throw std::runtime_error(input.error);
                values.push_back(input.cells.at(0));
            }
            data += Array("const double", "in_" + std::to_string(k), steps, values);
        }
        std::optional<int> inexact;  // where the interpreter's terms stop being exact
        for (std::size_t k = 0; k < compiled.sequences.size(); ++k) {
            const auto&              sequence = compiled.sequences[k];
            const std::size_t        cells    = sequence.rows * sequence.cols;
            const std::string        id = std::to_string(k), size = std::to_string(steps * cells);
            std::vector<std::string> want, known;
            for (int n = first; n < first + steps; ++n) {
                const Term term = At(session, instance + "." + sequence.name, n);
                if (!term.exact && (!inexact || n < *inexact)) inexact = n;
                for (std::size_t c = 0; c < cells; ++c) {
                    const bool given = term.error.empty();
                    want.push_back(given ? term.cells[c] : "0.0");
                    known.push_back(given ? "1" : "0");
                }
            }
            data += Array("const double", "want_" + id, steps * cells, want);
            data += Array("const unsigned char", "known_" + id, steps * cells, known);
            data += "static double got_" + id + "[" + size + "];\n";
            stepped += "        memcpy(&got_" + id + "[n * " + std::to_string(cells) + "], &m." +
                       sequence.name + "[0], sizeof(double) * " + std::to_string(cells) + ");\n";
            held += "    held &= hold_(\"" + instance + "." + sequence.name + "\", " +
                    std::to_string(sequence.cols) + ", " + std::to_string(cells) + ", got_" + id +
                    ", want_" + id + ", known_" + id + ");\n";
        }
        std::string arguments;
        for (std::size_t k = 0; k < compiled.inputs.size(); ++k)
            arguments += ", in_" + std::to_string(k) + "[n]";
        const std::string against = !inexact ? "exact values"
                                             : "exact values until " + std::to_string(*inexact) +
                                                   " and inexact ones from there";

        std::string out;
        out += "/* Generated by 'inkamath --check' from " + source + ": the instance\n";
        out += " * compiled, stepped on the inputs the interpreter gives it, and each term\n";
        out += " * held to the interpreter's. Build it as the header would be built. */\n";
        out += compiled.header + "\n#include <stdio.h>\n\n";
        out += "/* A term parts from the interpreter's where they differ by more than a\n";
        out += " * billionth of one plus the interpreter's term. */\n";
        out += "static int hold_(const char* name, int cols, int cells, const double* got,\n";
        out += "                 const double* want, const unsigned char* known) {\n";
        out += "    double worst = 0.0;\n";
        out += "    for (int k = 0; k < " + std::to_string(steps) + " * cells; ++k) {\n";
        out += "        const double difference = fabs(got[k] - want[k]);\n";
        out += "        if (!known[k]) continue;\n";
        out += "        if (!(difference <= 1e-9 * (1.0 + fabs(want[k])))) {\n";
        out += "            if (cells == 1)\n";
        out +=
            "                printf(\"%s: %.17g at %d, where the interpreter gives %.17g\\n\", "
            "name,\n";
        out += "                       got[k], " + index + "k, want[k]);\n";
        out += "            else\n";
        out +=
            "                printf(\"%s[%d,%d]: %.17g at %d, where the interpreter gives "
            "%.17g\\n\",\n";
        out += "                       name, k % cells / cols + 1, k % cells % cols + 1, got[k],\n";
        out += "                       " + index + "k / cells, want[k]);\n";
        out += "            return 0;\n        }\n";
        out += "        if (difference > worst) worst = difference;\n    }\n";
        out += "    printf(\"%s: within %.2g\\n\", name, worst);\n    return 1;\n}\n\n";
        out += data + "\nint main(void) {\n";
        out += "    " + module + " m;\n    int held = 1;\n    " + module + "_init(&m);\n";
        out += "    for (int n = 0; n < " + std::to_string(steps) + "; ++n) {\n";
        out += "        " + module + "_step(&m" + arguments + ");\n" + stepped + "    }\n";
        out += "    printf(\"" + instance + ": " + std::to_string(steps) + " steps from " +
               std::to_string(first) + ", against " + against + "\\n\");\n";
        out += held + "    return !held;\n}\n";
        return out;
    }

private:
    // The interpreter's term, each cell as C writes it, or why there is none.
    struct Term {
        std::vector<std::string> cells;
        bool                     exact = true;
        std::string              error;
    };

    static Term At(Interpreter<Number>& session, const std::string& name, int n) {
        const std::string term   = name + "_(" + std::to_string(n) + ")";
        const auto        result = session.Eval(term);
        Term              answer;
        if (const auto* diagnostic = std::get_if<Diagnostic>(&result)) {
            answer.error = term + ": " + diagnostic->message;
            return answer;
        }
        const auto* value = std::get_if<Interpreter<Number>::matrix_type>(&result);
        if (!value) {
            answer.error = term + " has no value";
            return answer;
        }
        for (std::size_t i = 1; i <= value->Size().rows; ++i) {
            for (std::size_t j = 1; j <= value->Size().cols; ++j) {
                const Number& cell = (*value)(i, j);
                const auto    z    = cell.Inexact();
                if (z.imag() != 0 || !std::isfinite(z.real())) {
                    answer.error = term + " is not a finite real number";
                    return answer;
                }
                answer.exact = answer.exact && cell.exact();
                char text[40];
                std::snprintf(text, sizeof text, "%.17g", z.real());
                answer.cells.emplace_back(text);
            }
        }
        return answer;
    }

    // Four values to a line, so that a term can be found by its index.
    static std::string Array(const std::string& type, const std::string& name, std::size_t size,
                             const std::vector<std::string>& values) {
        std::string out = "static " + type + " " + name + "[" + std::to_string(size) + "] = {";
        for (std::size_t k = 0; k < values.size(); ++k)
            out += (k % 4 == 0 ? "\n    " : " ") + values[k] + (k + 1 < values.size() ? "," : "");
        return out + "\n};\n";
    }
};

#endif  // INKAMATH_CHECK_HPP
