/* Generated by 'inkamath --compile' from inkamath_prelude.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. A compiler may also fuse a multiply and an
 * add, rounding once where the definitions round twice (-ffp-contract): often
 * closer to exact, but the step then depends on how it is built, so build
 * what 'inkamath --check' writes the way the step itself is built. */
#ifndef INKAMATH_PRELUDE_H
#define INKAMATH_PRELUDE_H

#include <math.h>
#include <string.h>

/* Using it:
 *
 *     inkamath_prelude m;
 *     inkamath_prelude_init(&m);
 *     inkamath_prelude_step(&m);  once for each index, the first 0
 *     m.c[0]  is then c_n
 *
 * A step takes no input. After a step, m.name[k] is name_(n-k) for each
 * sequence: c. A term the interpreter would refuse is NaN, and so is every
 * term that reads one, through a guard or a comparison as through arithmetic.
 * Built with -ffinite-math-only, which -ffast-math implies, GCC removes the
 * tests that make it so, and Clang warns of each NaN.
 */

/* The parameters, which the host may assign, then what derives from them,
 * then the index of the latest step and each sequence's terms from that
 * index back. */
typedef struct inkamath_prelude {
    long long index_;
    double c[1];
} inkamath_prelude;

static inline double inkamath_prelude_expp(double arg_r) {
    return arg_r * (1.0 + arg_r * (0.5 + arg_r * (0.16666666666666666 + arg_r * (0.041666666666666664 + arg_r * (0.008333333333333333 + arg_r * (0.001388888888888889 + arg_r * (0.0001984126984126984 + arg_r * (2.48015873015873e-05 + arg_r * (2.7557319223985893e-06 + arg_r * (2.755731922398589e-07 + arg_r * (2.505210838544172e-08 + arg_r * (2.08767569878681e-09 + arg_r * (1.6059043836821613e-10 + arg_r / 87178291200.0)))))))))))));
}

static inline double inkamath_prelude_expk(double arg_x, double arg_k) {
    return (1.0 + inkamath_prelude_expp(arg_x - arg_k * 355.0 / 512.0 + arg_k * 0.00021219444005469057)) * pow(2.0, arg_k - floor(arg_k / 2.0)) * pow(2.0, floor(arg_k / 2.0));
}

static inline double inkamath_prelude_exp(double arg_x) {
    return isnan(arg_x) ? NAN : arg_x > 1000.0 ? INFINITY : isnan(arg_x) ? NAN : arg_x < -1000.0 ? 0.0 : inkamath_prelude_expk(arg_x, floor(arg_x * 1.4426950408889634 + 0.5));
}

static inline double inkamath_prelude_ilogbs(double arg_x, double arg_k, double arg_s) {
    return isnan(arg_k + arg_s) ? NAN : arg_k + arg_s > 3321.0 ? arg_k : isnan(arg_x) || isnan(pow(2.0, arg_k + arg_s)) ? NAN : arg_x >= pow(2.0, arg_k + arg_s) ? arg_k + arg_s : arg_k;
}

static inline double inkamath_prelude_ilogb(double arg_x) {
    return isnan(arg_x) ? NAN : arg_x <= 0.0 ? NAN : inkamath_prelude_ilogbs(arg_x, inkamath_prelude_ilogbs(arg_x, inkamath_prelude_ilogbs(arg_x, inkamath_prelude_ilogbs(arg_x, inkamath_prelude_ilogbs(arg_x, inkamath_prelude_ilogbs(arg_x, inkamath_prelude_ilogbs(arg_x, inkamath_prelude_ilogbs(arg_x, inkamath_prelude_ilogbs(arg_x, inkamath_prelude_ilogbs(arg_x, inkamath_prelude_ilogbs(arg_x, inkamath_prelude_ilogbs(arg_x, inkamath_prelude_ilogbs(arg_x, -4096.0, 4096.0), 2048.0), 1024.0), 512.0), 256.0), 128.0), 64.0), 32.0), 16.0), 8.0), 4.0), 2.0), 1.0);
}

static inline double inkamath_prelude_logp(double arg_z) {
    return 1.0 + arg_z * (0.3333333333333333 + arg_z * (0.2 + arg_z * (0.14285714285714285 + arg_z * (0.1111111111111111 + arg_z * (0.09090909090909091 + arg_z * (0.07692307692307693 + arg_z * (0.06666666666666667 + arg_z * (0.058823529411764705 + arg_z * (0.05263157894736842 + arg_z / 21.0)))))))));
}

static inline double inkamath_prelude_logs(double arg_s, double arg_k) {
    return arg_k * 355.0 / 512.0 + (2.0 * arg_s * inkamath_prelude_logp(arg_s * arg_s) - arg_k * 0.00021219444005469057);
}

static inline double inkamath_prelude_logm(double arg_m, double arg_k) {
    return isnan(arg_m * arg_m) ? NAN : arg_m * arg_m > 2.0 ? inkamath_prelude_logs((arg_m / 2.0 - 1.0) / (arg_m / 2.0 + 1.0), arg_k + 1.0) : inkamath_prelude_logs((arg_m - 1.0) / (arg_m + 1.0), arg_k);
}

static inline double inkamath_prelude_logk(double arg_x, double arg_k) {
    return inkamath_prelude_logm(arg_x / pow(2.0, arg_k), arg_k);
}

static inline double inkamath_prelude_log(double arg_x) {
    return isnan(arg_x) ? NAN : arg_x <= 0.0 ? NAN : isnan(2.0 * arg_x) || isnan(arg_x) ? NAN : 2.0 * arg_x == arg_x ? arg_x : inkamath_prelude_logk(arg_x, inkamath_prelude_ilogb(arg_x));
}

static inline double inkamath_prelude_tanhe(double arg_m) {
    return (0.0 - arg_m) / (arg_m + 2.0);
}

static inline double inkamath_prelude_tanhk(double arg_y, double arg_k) {
    return inkamath_prelude_tanhe(pow(2.0, arg_k) - 1.0 + pow(2.0, arg_k) * inkamath_prelude_expp(arg_y - arg_k * 355.0 / 512.0 + arg_k * 0.00021219444005469057));
}

static inline double inkamath_prelude_tanhp(double arg_x) {
    return isnan(arg_x) ? NAN : arg_x > 20.0 ? 1.0 : inkamath_prelude_tanhk(-2.0 * arg_x, floor(-2.0 * arg_x * 1.4426950408889634 + 0.5));
}

static inline double inkamath_prelude_tanh(double arg_x) {
    return isnan(arg_x) ? NAN : arg_x < 0.0 ? 0.0 - inkamath_prelude_tanhp(0.0 - arg_x) : inkamath_prelude_tanhp(arg_x);
}

/* Computes what derives from the parameters: call it after assigning one. */
static inline void inkamath_prelude_update(inkamath_prelude* m_) {
    (void)m_;
}

static inline void inkamath_prelude_init(inkamath_prelude* m_) {
    memset(m_, 0, sizeof *m_);
    m_->index_ = -1;
    inkamath_prelude_update(m_);
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void inkamath_prelude_step(inkamath_prelude* m_) {
    ++m_->index_;
    m_->c[0] = inkamath_prelude_exp((double)m_->index_) + inkamath_prelude_log((double)m_->index_ + 1.0) + inkamath_prelude_tanh((double)m_->index_) + inkamath_prelude_ilogb((double)m_->index_ + 1.0);
}

#endif
