/* Generated by 'inkamath --compile' from adc.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. */
#ifndef ADC_H
#define ADC_H

#include <math.h>
#include <string.h>

/* Using it:
 *
 *     adc m;
 *     adc_init(&m);
 *     adc_step(&m, x);  once for each index, the first 0
 *     m.rising[0]  is then rising_n
 *
 * A step takes x_n, the input at its index. After a step, m.name[k] is
 * name_(n-k) for each sequence: x, v, held (k <= 1), alarm and rising. The
 * parameters are fields holding the file's values once adc_init has run: hi =
 * 1.0, lo = -1.0 and q = 0.25. After assigning one, call adc_update.
 */

/* The parameters, which the host may assign, then what derives from them,
 * then the index of the latest step and each sequence's terms from that
 * index back. */
typedef struct adc {
    double hi;
    double lo;
    double q;
    long long index_;
    double x[1];
    double v[1];
    double held[2];
    double alarm[1];
    double rising[1];
} adc;

/* Computes what derives from the parameters: call it after assigning one. */
static inline void adc_update(adc* m_) {
    (void)m_;
}

static inline void adc_init(adc* m_) {
    memset(m_, 0, sizeof *m_);
    m_->hi = 1.0;
    m_->lo = -1.0;
    m_->q = 0.25;
    m_->index_ = -1;
    adc_update(m_);
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void adc_step(adc* m_, double x) {
    ++m_->index_;
    m_->held[1] = m_->held[0];
    m_->x[0] = x;
    m_->v[0] = m_->q * floor(m_->x[0] / m_->q);
    m_->held[0] = m_->index_ == 0 ? 0.0 : m_->held[1] - m_->v[0] < m_->q && m_->v[0] - m_->held[1] < m_->q ? m_->held[1] : m_->v[0];
    m_->alarm[0] = (m_->held[0] < m_->lo || m_->held[0] > m_->hi ? 1.0 : 0.0);
    const double t0_ = ((double)m_->index_ > 0.0 ? 1.0 : 0.0);
    m_->rising[0] = (t0_ == 0.0 ? 0.0 : t0_ != t0_ ? NAN : (m_->index_ < 1 ? NAN : (m_->held[0] > m_->held[1] ? 1.0 : 0.0)));
}

#endif
