/* Generated by 'inkamath --compile' from back.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. A compiler may also fuse a multiply and an
 * add, rounding once where the definitions round twice (-ffp-contract): often
 * closer to exact, but the step then depends on how it is built, so build
 * what 'inkamath --check' writes the way the step itself is built. */
#ifndef BACK_H
#define BACK_H

#include <math.h>
#include <string.h>

/* Using it:
 *
 *     back m;
 *     back_init(&m);
 *     back_step(&m, u);  once for each index, the first 0
 *     m.e[0]  is then e_n
 *
 * A step takes u_n, the input at its index. After a step, m.name[k] is
 * name_(n-k) for each sequence: u (k <= 2), a (k <= 1), b, c (k <= 1) and e. A
 * term the interpreter would refuse is NaN, and so is every term that reads
 * one, through a guard or a comparison as through arithmetic;
 * -ffinite-math-only, which -ffast-math implies, removes the tests that make
 * it so.
 */

/* The parameters, which the host may assign, then what derives from them,
 * then the index of the latest step and each sequence's terms from that
 * index back. */
typedef struct back {
    long long index_;
    double u[3];
    double a[2];
    double b[1];
    double c[2];
    double e[1];
} back;

/* Computes what derives from the parameters: call it after assigning one. */
static inline void back_update(back* m_) {
    (void)m_;
}

static inline void back_init(back* m_) {
    memset(m_, 0, sizeof *m_);
    m_->index_ = -1;
    back_update(m_);
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void back_step(back* m_, double u) {
    ++m_->index_;
    m_->u[2] = m_->u[1];
    m_->u[1] = m_->u[0];
    m_->a[1] = m_->a[0];
    m_->c[1] = m_->c[0];
    m_->u[0] = u;
    m_->a[0] = (double)m_->index_ > 2.0 ? (m_->index_ < 1 ? NAN : m_->u[1]) : 0.125;
    m_->b[0] = (m_->index_ < 1 ? (double)(m_->index_ - 1) > 2.0 ? m_->index_ < 2 ? NAN : m_->u[2] : 0.125 : m_->a[1]) / 2.0;
    m_->c[0] = (double)m_->index_ < 0.0 ? (m_->index_ < 1 ? NAN : m_->u[1]) : 1.0;
    m_->e[0] = (m_->index_ < 1 ? (double)(m_->index_ - 1) < 0.0 ? m_->index_ < 2 ? NAN : m_->u[2] : 1.0 : m_->c[1]);
}

#endif
