/* Generated by 'inkamath --compile' from bank.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. */
#ifndef BANK_H
#define BANK_H

#include <math.h>
#include <string.h>

/* Using it:
 *
 *     bank m;
 *     bank_init(&m);
 *     bank_step(&m, x);  once for each index, the first 0
 *     m.y[0]  is then y_n
 *
 * A step takes x_n, the input at its index. After a step, m.name[k] is
 * name_(n-k) for each sequence: x, bank_smooth_1.u, bank_smooth_1.v (k <= 1),
 * bank_smooth_2.u, bank_smooth_2.v (k <= 1), bank_smooth_3.u,
 * bank_smooth_3.v (k <= 1), bank, y_smooth.u, y_smooth.v (k <= 1) and y. The
 * parameters are fields holding the file's values once bank_init has run:
 * bank_smooth_1.a = 0.25, bank_smooth_2.a = 0.5, bank_smooth_3.a = 0.75 and
 * y_smooth.a = 0.5. After assigning one, call bank_update.
 */

/* The parameters, which the host may assign, then what derives from them,
 * then the index of the latest step and each sequence's terms from that
 * index back. */
typedef struct bank {
    long long index_;
    double x[1];
    double bank[1][3][1];
    double y[1];
    struct {
        double a;
        double u[1];
        double v[2];
    } bank_smooth_1;
    struct {
        double a;
        double u[1];
        double v[2];
    } bank_smooth_2;
    struct {
        double a;
        double u[1];
        double v[2];
    } bank_smooth_3;
    struct {
        double a;
        double u[1];
        double v[2];
    } y_smooth;
} bank;

/* Computes what derives from the parameters: call it after assigning one. */
static inline void bank_update(bank* m_) {
    (void)m_;
}

static inline void bank_init(bank* m_) {
    memset(m_, 0, sizeof *m_);
    m_->bank_smooth_1.a = 0.25;
    m_->bank_smooth_2.a = 0.5;
    m_->bank_smooth_3.a = 0.75;
    m_->y_smooth.a = 0.5;
    m_->index_ = -1;
    bank_update(m_);
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void bank_step(bank* m_, double x) {
    ++m_->index_;
    m_->bank_smooth_1.v[1] = m_->bank_smooth_1.v[0];
    m_->bank_smooth_2.v[1] = m_->bank_smooth_2.v[0];
    m_->bank_smooth_3.v[1] = m_->bank_smooth_3.v[0];
    m_->y_smooth.v[1] = m_->y_smooth.v[0];
    m_->x[0] = x;
    m_->bank_smooth_1.u[0] = m_->x[0];
    m_->bank_smooth_1.v[0] = m_->index_ == 0 ? 0.0 : m_->bank_smooth_1.a * m_->bank_smooth_1.u[0] + (1.0 - m_->bank_smooth_1.a) * m_->bank_smooth_1.v[1];
    m_->bank_smooth_2.u[0] = m_->x[0];
    m_->bank_smooth_2.v[0] = m_->index_ == 0 ? 0.0 : m_->bank_smooth_2.a * m_->bank_smooth_2.u[0] + (1.0 - m_->bank_smooth_2.a) * m_->bank_smooth_2.v[1];
    m_->bank_smooth_3.u[0] = m_->x[0];
    m_->bank_smooth_3.v[0] = m_->index_ == 0 ? 0.0 : m_->bank_smooth_3.a * m_->bank_smooth_3.u[0] + (1.0 - m_->bank_smooth_3.a) * m_->bank_smooth_3.v[1];
    m_->bank[0][0][0] = m_->bank_smooth_1.v[0];
    m_->bank[0][1][0] = m_->bank_smooth_2.v[0];
    m_->bank[0][2][0] = m_->bank_smooth_3.v[0];
    m_->y_smooth.u[0] = m_->bank[0][2][0];
    m_->y_smooth.v[0] = m_->index_ == 0 ? 0.0 : m_->y_smooth.a * m_->y_smooth.u[0] + (1.0 - m_->y_smooth.a) * m_->y_smooth.v[1];
    m_->y[0] = m_->y_smooth.v[0];
}

#endif
