/* Generated by 'inkamath --compile' from chain.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. A compiler may also fuse a multiply and an
 * add, rounding once where the definitions round twice (-ffp-contract): often
 * closer to exact, but the step then depends on how it is built, so build
 * what 'inkamath --check' writes the way the step itself is built. */
#ifndef CHAIN_H
#define CHAIN_H

#include <math.h>
#include <string.h>

/* Using it:
 *
 *     chain m;
 *     chain_init(&m);
 *     chain_step(&m, x);  once for each index, the first 0
 *     m.y[0]  is then y_n
 *
 * A step takes x_n, the input at its index. After a step, m.name[k] is
 * name_(n-k) for each sequence: x, fast.u, fast.v (k <= 1), h.u, h.low.u,
 * h.low.v (k <= 1), h.v, slow.u, slow.v (k <= 1) and y. The parameters are
 * fields holding the file's values once chain_init has run: h.a = 0.25,
 * k = 0.5 and slow.a = 0.1. After assigning one, call chain_update.
 */

/* The parameters, which the host may assign, then what derives from them,
 * then the index of the latest step and each sequence's terms from that
 * index back. */
typedef struct chain {
    double k;
    long long index_;
    double x[1];
    double y[1];
    struct {
        double u[1];
        double v[2];
    } fast;
    struct {
        double a;
        double u[1];
        double v[1];
        struct {
            double u[1];
            double v[2];
        } low;
    } h;
    struct {
        double a;
        double u[1];
        double v[2];
    } slow;
} chain;

/* Computes what derives from the parameters: call it after assigning one. */
static inline void chain_update(chain* m_) {
    (void)m_;
}

static inline void chain_init(chain* m_) {
    memset(m_, 0, sizeof *m_);
    m_->h.a = 0.25;
    m_->k = 0.5;
    m_->slow.a = 0.1;
    m_->index_ = -1;
    chain_update(m_);
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void chain_step(chain* m_, double x) {
    ++m_->index_;
    m_->fast.v[1] = m_->fast.v[0];
    m_->h.low.v[1] = m_->h.low.v[0];
    m_->slow.v[1] = m_->slow.v[0];
    m_->x[0] = x;
    m_->fast.u[0] = m_->x[0];
    m_->fast.v[0] = m_->index_ == 0 ? 0.0 : m_->k * m_->fast.u[0] + (1.0 + (0.0 - m_->k)) * m_->fast.v[1];
    m_->h.u[0] = m_->x[0];
    m_->h.low.u[0] = m_->h.u[0];
    m_->h.low.v[0] = m_->index_ == 0 ? 0.0 : m_->h.a * m_->h.low.u[0] + (1.0 + (0.0 - m_->h.a)) * m_->h.low.v[1];
    m_->h.v[0] = m_->h.u[0] + (0.0 - m_->h.low.v[0]);
    m_->slow.u[0] = m_->fast.v[0];
    m_->slow.v[0] = m_->index_ == 0 ? 0.0 : m_->slow.a * m_->slow.u[0] + (1.0 + (0.0 - m_->slow.a)) * m_->slow.v[1];
    m_->y[0] = m_->slow.v[0] + m_->h.v[0] + 0.1;
}

#endif
