/* Generated by 'inkamath --compile' from fir.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. */
#ifndef FIR_H
#define FIR_H

#include <math.h>
#include <string.h>

/* Using it:
 *
 *     fir m;
 *     fir_init(&m);
 *     fir_step(&m, x);  once for each index, the first 0
 *     m.y[0]  is then y_n
 *
 * A step takes x_n, the input at its index. After a step, m.name[k] is
 * name_(n-k) for each sequence: x (k <= 3) and y. The parameters are fields
 * holding the file's values once fir_init has run: b (1x4). After assigning
 * one, call fir_update.
 */

/* The parameters, which the host may assign, then what derives from them,
 * then the index of the latest step and each sequence's terms from that
 * index back. */
typedef struct fir {
    double b[1][4];
    long long index_;
    double x[4];
    double y[1];
} fir;

/* Computes what derives from the parameters: call it after assigning one. */
static inline void fir_update(fir* m_) {
    (void)m_;
}

static inline void fir_init(fir* m_) {
    memset(m_, 0, sizeof *m_);
    m_->b[0][0] = 0.1;
    m_->b[0][1] = 0.2;
    m_->b[0][2] = 0.3;
    m_->b[0][3] = 0.4;
    m_->index_ = -1;
    fir_update(m_);
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void fir_step(fir* m_, double x) {
    ++m_->index_;
    m_->x[3] = m_->x[2];
    m_->x[2] = m_->x[1];
    m_->x[1] = m_->x[0];
    m_->x[0] = x;
    if (m_->index_ >= 3) {
        m_->y[0] = m_->b[0][0] * m_->x[0] + m_->b[0][1] * m_->x[1] + m_->b[0][2] * m_->x[2] + m_->b[0][3] * m_->x[3];
    }
}

#endif
