/* Generated by 'inkamath --compile' from heat.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. */
#ifndef HEAT_H
#define HEAT_H

#include <math.h>
#include <string.h>

/* The parameters, which the host may assign, then what derives from them,
 * then the index of the latest step and each sequence's terms from that
 * index back. */
typedef struct heat {
    double B[3][1];
    double I[3][3];
    double dt;
    double h;
    double K[3][3];
    double A[3][3];
    long long index_;
    double q[1];
    double u[2][3][1];
} heat;

/* The inverse of a 3x3 matrix, in place, as the interpreter takes it: Gauss-Jordan
 * on the largest pivot, and NaN in every cell where there is none. */
static inline void heat_inverse3_(double a[3][3]) {
    double r[3][3];
    for (int i = 0; i < 3; ++i)
        for (int j = 0; j < 3; ++j) r[i][j] = i == j;
    for (int col = 0; col < 3; ++col) {
        int pivot = col;
        for (int row = col + 1; row < 3; ++row)
            if (fabs(a[row][col]) > fabs(a[pivot][col]) ||
                (a[pivot][col] == 0.0 && a[row][col] != 0.0))
                pivot = row;
        if (a[pivot][col] == 0.0) {
            for (int i = 0; i < 3; ++i)
                for (int j = 0; j < 3; ++j) a[i][j] = NAN;
            return;
        }
        for (int j = 0; j < 3; ++j) {
            const double s = a[pivot][j], t = r[pivot][j];
            a[pivot][j] = a[col][j];
            r[pivot][j] = r[col][j];
            a[col][j]   = s;
            r[col][j]   = t;
        }
        const double scale = a[col][col];
        for (int j = 0; j < 3; ++j) {
            a[col][j] = a[col][j] / scale;
            r[col][j] = r[col][j] / scale;
        }
        for (int row = 0; row < 3; ++row) {
            const double factor = a[row][col];
            if (row == col || factor == 0.0) continue;
            for (int j = 0; j < 3; ++j) {
                a[row][j] = a[row][j] - factor * a[col][j];
                r[row][j] = r[row][j] - factor * r[col][j];
            }
        }
    }
    memcpy(a, r, sizeof r);
}

/* Computes what derives from the parameters: call it after assigning one. */
static inline void heat_update(heat* m_) {
    m_->K[0][0] = 2.0 / m_->h;
    m_->K[0][1] = -1.0 / m_->h;
    m_->K[0][2] = 0.0;
    m_->K[1][0] = -1.0 / m_->h;
    m_->K[1][1] = 2.0 / m_->h;
    m_->K[1][2] = -1.0 / m_->h;
    m_->K[2][0] = 0.0;
    m_->K[2][1] = -1.0 / m_->h;
    m_->K[2][2] = 2.0 / m_->h;
    double t0_[3][3] = {{m_->h * m_->I[0][0] + m_->dt * m_->K[0][0], m_->h * m_->I[0][1] + m_->dt * m_->K[0][1], m_->h * m_->I[0][2] + m_->dt * 0.0}, {m_->h * m_->I[1][0] + m_->dt * m_->K[1][0], m_->h * m_->I[1][1] + m_->dt * m_->K[1][1], m_->h * m_->I[1][2] + m_->dt * m_->K[1][2]}, {m_->h * m_->I[2][0] + m_->dt * 0.0, m_->h * m_->I[2][1] + m_->dt * m_->K[2][1], m_->h * m_->I[2][2] + m_->dt * m_->K[2][2]}};
    heat_inverse3_(t0_);
    m_->A[0][0] = t0_[0][0] * m_->h;
    m_->A[0][1] = t0_[0][1] * m_->h;
    m_->A[0][2] = t0_[0][2] * m_->h;
    m_->A[1][0] = t0_[1][0] * m_->h;
    m_->A[1][1] = t0_[1][1] * m_->h;
    m_->A[1][2] = t0_[1][2] * m_->h;
    m_->A[2][0] = t0_[2][0] * m_->h;
    m_->A[2][1] = t0_[2][1] * m_->h;
    m_->A[2][2] = t0_[2][2] * m_->h;
}

static inline void heat_init(heat* m_) {
    memset(m_, 0, sizeof *m_);
    m_->B[0][0] = 1.0;
    m_->B[1][0] = 0.0;
    m_->B[2][0] = 0.0;
    m_->I[0][0] = 1.0;
    m_->I[0][1] = 0.0;
    m_->I[0][2] = 0.0;
    m_->I[1][0] = 0.0;
    m_->I[1][1] = 1.0;
    m_->I[1][2] = 0.0;
    m_->I[2][0] = 0.0;
    m_->I[2][1] = 0.0;
    m_->I[2][2] = 1.0;
    m_->dt = 0.01;
    m_->h = 0.25;
    m_->index_ = -1;
    heat_update(m_);
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void heat_step(heat* m_, double q) {
    ++m_->index_;
    memcpy(m_->u[1], m_->u[0], sizeof m_->u[1]);
    m_->q[0] = q;
    const double t1_ = m_->u[1][0][0] + m_->dt * m_->B[0][0] * m_->q[0];
    const double t2_ = m_->u[1][1][0] + m_->dt * m_->B[1][0] * m_->q[0];
    const double t3_ = m_->u[1][2][0] + m_->dt * m_->B[2][0] * m_->q[0];
    m_->u[0][0][0] = m_->index_ == 0 ? 0.0 * m_->B[0][0] : m_->A[0][0] * t1_ + m_->A[0][1] * t2_ + m_->A[0][2] * t3_;
    m_->u[0][1][0] = m_->index_ == 0 ? 0.0 * m_->B[1][0] : m_->A[1][0] * t1_ + m_->A[1][1] * t2_ + m_->A[1][2] * t3_;
    m_->u[0][2][0] = m_->index_ == 0 ? 0.0 * m_->B[2][0] : m_->A[2][0] * t1_ + m_->A[2][1] * t2_ + m_->A[2][2] * t3_;
}

#endif
