/* Generated by 'inkamath --compile' from kalman.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. */
#ifndef KALMAN_H
#define KALMAN_H

#include <math.h>
#include <string.h>

/* The parameters, which the host may assign, then the index of the latest
 * step and each sequence's terms from that index back. */
typedef struct kalman {
    double H[1][2];
    double I2[2][2];
    double Q[2][2];
    double R;
    double dt;
    long long index_;
    double z[1];
    double Pp[1][2][2];
    double K[1][2][1];
    double P[2][2][2];
    double xp[1][2][1];
    double x[2][2][1];
} kalman;

static inline void kalman_init(kalman* m_) {
    memset(m_, 0, sizeof *m_);
    m_->H[0][0] = 1.0;
    m_->H[0][1] = 0.0;
    m_->I2[0][0] = 1.0;
    m_->I2[0][1] = 0.0;
    m_->I2[1][0] = 0.0;
    m_->I2[1][1] = 1.0;
    m_->Q[0][0] = 0.01;
    m_->Q[0][1] = 0.0;
    m_->Q[1][0] = 0.0;
    m_->Q[1][1] = 0.01;
    m_->R = 1.0;
    m_->dt = 1.0;
    m_->index_ = -1;
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void kalman_step(kalman* m_, double z) {
    ++m_->index_;
    memcpy(m_->P[1], m_->P[0], sizeof m_->P[1]);
    memcpy(m_->x[1], m_->x[0], sizeof m_->x[1]);
    m_->z[0] = z;
    if (m_->index_ >= 1) {
        m_->Pp[0][0][0] = (1.0 * m_->P[1][0][0] + m_->dt * m_->P[1][1][0]) * 1.0 + (1.0 * m_->P[1][0][1] + m_->dt * m_->P[1][1][1]) * m_->dt + m_->Q[0][0];
        m_->Pp[0][0][1] = (1.0 * m_->P[1][0][0] + m_->dt * m_->P[1][1][0]) * 0.0 + (1.0 * m_->P[1][0][1] + m_->dt * m_->P[1][1][1]) * 1.0 + m_->Q[0][1];
        m_->Pp[0][1][0] = (0.0 * m_->P[1][0][0] + 1.0 * m_->P[1][1][0]) * 1.0 + (0.0 * m_->P[1][0][1] + 1.0 * m_->P[1][1][1]) * m_->dt + m_->Q[1][0];
        m_->Pp[0][1][1] = (0.0 * m_->P[1][0][0] + 1.0 * m_->P[1][1][0]) * 0.0 + (0.0 * m_->P[1][0][1] + 1.0 * m_->P[1][1][1]) * 1.0 + m_->Q[1][1];
    }
    if (m_->index_ >= 1) {
        m_->K[0][0][0] = (m_->Pp[0][0][0] * m_->H[0][0] + m_->Pp[0][0][1] * m_->H[0][1]) * pow((m_->H[0][0] * m_->Pp[0][0][0] + m_->H[0][1] * m_->Pp[0][1][0]) * m_->H[0][0] + (m_->H[0][0] * m_->Pp[0][0][1] + m_->H[0][1] * m_->Pp[0][1][1]) * m_->H[0][1] + m_->R, -1.0);
        m_->K[0][1][0] = (m_->Pp[0][1][0] * m_->H[0][0] + m_->Pp[0][1][1] * m_->H[0][1]) * pow((m_->H[0][0] * m_->Pp[0][0][0] + m_->H[0][1] * m_->Pp[0][1][0]) * m_->H[0][0] + (m_->H[0][0] * m_->Pp[0][0][1] + m_->H[0][1] * m_->Pp[0][1][1]) * m_->H[0][1] + m_->R, -1.0);
    }
    m_->P[0][0][0] = m_->index_ == 0 ? 10.0 : (m_->I2[0][0] - m_->K[0][0][0] * m_->H[0][0]) * m_->Pp[0][0][0] + (m_->I2[0][1] - m_->K[0][0][0] * m_->H[0][1]) * m_->Pp[0][1][0];
    m_->P[0][0][1] = m_->index_ == 0 ? 0.0 : (m_->I2[0][0] - m_->K[0][0][0] * m_->H[0][0]) * m_->Pp[0][0][1] + (m_->I2[0][1] - m_->K[0][0][0] * m_->H[0][1]) * m_->Pp[0][1][1];
    m_->P[0][1][0] = m_->index_ == 0 ? 0.0 : (m_->I2[1][0] - m_->K[0][1][0] * m_->H[0][0]) * m_->Pp[0][0][0] + (m_->I2[1][1] - m_->K[0][1][0] * m_->H[0][1]) * m_->Pp[0][1][0];
    m_->P[0][1][1] = m_->index_ == 0 ? 10.0 : (m_->I2[1][0] - m_->K[0][1][0] * m_->H[0][0]) * m_->Pp[0][0][1] + (m_->I2[1][1] - m_->K[0][1][0] * m_->H[0][1]) * m_->Pp[0][1][1];
    if (m_->index_ >= 1) {
        m_->xp[0][0][0] = 1.0 * m_->x[1][0][0] + m_->dt * m_->x[1][1][0];
        m_->xp[0][1][0] = 0.0 * m_->x[1][0][0] + 1.0 * m_->x[1][1][0];
    }
    m_->x[0][0][0] = m_->index_ == 0 ? 0.0 : m_->xp[0][0][0] + m_->K[0][0][0] * (m_->z[0] - (m_->H[0][0] * m_->xp[0][0][0] + m_->H[0][1] * m_->xp[0][1][0]));
    m_->x[0][1][0] = m_->index_ == 0 ? 0.0 : m_->xp[0][1][0] + m_->K[0][1][0] * (m_->z[0] - (m_->H[0][0] * m_->xp[0][0][0] + m_->H[0][1] * m_->xp[0][1][0]));
}

#endif
