/* Generated by 'inkamath --compile' from kalman2.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. */
#ifndef KALMAN2_H
#define KALMAN2_H

#include <math.h>
#include <string.h>

/* Using it:
 *
 *     kalman2 m;
 *     kalman2_init(&m);
 *     kalman2_step(&m, zp, zs);  once for each index, the first 0
 *     m.x[0][i][j]  is then x_n, row i+1 and column j+1
 *
 * A step takes zp_n and zs_n, the inputs at its index. After a step, m.name[k]
 * is name_(n-k) for each sequence: zp, zs, Pp, K, P (k <= 1), xp, z and
 * x (k <= 1). The parameters are fields holding the file's values once
 * kalman2_init has run: H (2x2), I (2x2), Q (2x2), R (2x2) and dt = 1.0. After
 * assigning one, call kalman2_update.
 */

/* The parameters, which the host may assign, then what derives from them,
 * then the index of the latest step and each sequence's terms from that
 * index back. */
typedef struct kalman2 {
    double H[2][2];
    double I[2][2];
    double Q[2][2];
    double R[2][2];
    double dt;
    long long index_;
    double zp[1];
    double zs[1];
    double Pp[1][2][2];
    double K[1][2][2];
    double P[2][2][2];
    double xp[1][2][1];
    double z[1][2][1];
    double x[2][2][1];
} kalman2;

/* The inverse of a 2x2 matrix, in place, as the interpreter takes it: Gauss-Jordan
 * on the largest pivot, and NaN in every cell where there is none. */
static inline void kalman2_inverse2_(double a[2][2]) {
    double r[2][2];
    for (int i = 0; i < 2; ++i)
        for (int j = 0; j < 2; ++j) r[i][j] = i == j;
    for (int col = 0; col < 2; ++col) {
        int pivot = col;
        for (int row = col + 1; row < 2; ++row)
            if (fabs(a[row][col]) > fabs(a[pivot][col]) ||
                (a[pivot][col] == 0.0 && a[row][col] != 0.0))
                pivot = row;
        if (a[pivot][col] == 0.0) {
            for (int i = 0; i < 2; ++i)
                for (int j = 0; j < 2; ++j) a[i][j] = NAN;
            return;
        }
        for (int j = 0; j < 2; ++j) {
            const double s = a[pivot][j], t = r[pivot][j];
            a[pivot][j] = a[col][j];
            r[pivot][j] = r[col][j];
            a[col][j]   = s;
            r[col][j]   = t;
        }
        const double scale = a[col][col];
        for (int j = 0; j < 2; ++j) {
            a[col][j] = a[col][j] / scale;
            r[col][j] = r[col][j] / scale;
        }
        for (int row = 0; row < 2; ++row) {
            const double factor = a[row][col];
            if (row == col || factor == 0.0) continue;
            for (int j = 0; j < 2; ++j) {
                a[row][j] = a[row][j] - factor * a[col][j];
                r[row][j] = r[row][j] - factor * r[col][j];
            }
        }
    }
    memcpy(a, r, sizeof r);
}

/* Computes what derives from the parameters: call it after assigning one. */
static inline void kalman2_update(kalman2* m_) {
    (void)m_;
}

static inline void kalman2_init(kalman2* m_) {
    memset(m_, 0, sizeof *m_);
    m_->H[0][0] = 1.0;
    m_->H[0][1] = 0.0;
    m_->H[1][0] = 1.0;
    m_->H[1][1] = 1.0;
    m_->I[0][0] = 1.0;
    m_->I[0][1] = 0.0;
    m_->I[1][0] = 0.0;
    m_->I[1][1] = 1.0;
    m_->Q[0][0] = 0.01;
    m_->Q[0][1] = 0.0;
    m_->Q[1][0] = 0.0;
    m_->Q[1][1] = 0.01;
    m_->R[0][0] = 1.0;
    m_->R[0][1] = 0.0;
    m_->R[1][0] = 0.0;
    m_->R[1][1] = 0.25;
    m_->dt = 1.0;
    m_->index_ = -1;
    kalman2_update(m_);
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void kalman2_step(kalman2* m_, double zp, double zs) {
    ++m_->index_;
    memcpy(m_->P[1], m_->P[0], sizeof m_->P[1]);
    memcpy(m_->x[1], m_->x[0], sizeof m_->x[1]);
    m_->zp[0] = zp;
    m_->zs[0] = zs;
    if (m_->index_ >= 1) {
        const double t0_ = 1.0 * m_->P[1][0][0] + m_->dt * m_->P[1][1][0];
        const double t1_ = 1.0 * m_->P[1][0][1] + m_->dt * m_->P[1][1][1];
        const double t2_ = 0.0 * m_->P[1][0][0] + 1.0 * m_->P[1][1][0];
        const double t3_ = 0.0 * m_->P[1][0][1] + 1.0 * m_->P[1][1][1];
        m_->Pp[0][0][0] = t0_ * 1.0 + t1_ * m_->dt + m_->Q[0][0];
        m_->Pp[0][0][1] = t0_ * 0.0 + t1_ * 1.0 + m_->Q[0][1];
        m_->Pp[0][1][0] = t2_ * 1.0 + t3_ * m_->dt + m_->Q[1][0];
        m_->Pp[0][1][1] = t2_ * 0.0 + t3_ * 1.0 + m_->Q[1][1];
    }
    if (m_->index_ >= 1) {
        const double t4_ = m_->H[0][0] * m_->Pp[0][0][0] + m_->H[0][1] * m_->Pp[0][1][0];
        const double t5_ = m_->H[0][0] * m_->Pp[0][0][1] + m_->H[0][1] * m_->Pp[0][1][1];
        const double t6_ = m_->H[1][0] * m_->Pp[0][0][0] + m_->H[1][1] * m_->Pp[0][1][0];
        const double t7_ = m_->H[1][0] * m_->Pp[0][0][1] + m_->H[1][1] * m_->Pp[0][1][1];
        double t8_[2][2] = {{t4_ * m_->H[0][0] + t5_ * m_->H[0][1] + m_->R[0][0], t4_ * m_->H[1][0] + t5_ * m_->H[1][1] + m_->R[0][1]}, {t6_ * m_->H[0][0] + t7_ * m_->H[0][1] + m_->R[1][0], t6_ * m_->H[1][0] + t7_ * m_->H[1][1] + m_->R[1][1]}};
        kalman2_inverse2_(t8_);
        const double t9_ = m_->Pp[0][0][0] * m_->H[0][0] + m_->Pp[0][0][1] * m_->H[0][1];
        const double t10_ = m_->Pp[0][0][0] * m_->H[1][0] + m_->Pp[0][0][1] * m_->H[1][1];
        const double t11_ = m_->Pp[0][1][0] * m_->H[0][0] + m_->Pp[0][1][1] * m_->H[0][1];
        const double t12_ = m_->Pp[0][1][0] * m_->H[1][0] + m_->Pp[0][1][1] * m_->H[1][1];
        m_->K[0][0][0] = t9_ * t8_[0][0] + t10_ * t8_[1][0];
        m_->K[0][0][1] = t9_ * t8_[0][1] + t10_ * t8_[1][1];
        m_->K[0][1][0] = t11_ * t8_[0][0] + t12_ * t8_[1][0];
        m_->K[0][1][1] = t11_ * t8_[0][1] + t12_ * t8_[1][1];
    }
    const double t13_ = m_->I[0][0] - (m_->K[0][0][0] * m_->H[0][0] + m_->K[0][0][1] * m_->H[1][0]);
    const double t14_ = m_->I[0][1] - (m_->K[0][0][0] * m_->H[0][1] + m_->K[0][0][1] * m_->H[1][1]);
    const double t15_ = m_->I[1][0] - (m_->K[0][1][0] * m_->H[0][0] + m_->K[0][1][1] * m_->H[1][0]);
    const double t16_ = m_->I[1][1] - (m_->K[0][1][0] * m_->H[0][1] + m_->K[0][1][1] * m_->H[1][1]);
    m_->P[0][0][0] = m_->index_ == 0 ? 10.0 : t13_ * m_->Pp[0][0][0] + t14_ * m_->Pp[0][1][0];
    m_->P[0][0][1] = m_->index_ == 0 ? 0.0 : t13_ * m_->Pp[0][0][1] + t14_ * m_->Pp[0][1][1];
    m_->P[0][1][0] = m_->index_ == 0 ? 0.0 : t15_ * m_->Pp[0][0][0] + t16_ * m_->Pp[0][1][0];
    m_->P[0][1][1] = m_->index_ == 0 ? 10.0 : t15_ * m_->Pp[0][0][1] + t16_ * m_->Pp[0][1][1];
    if (m_->index_ >= 1) {
        m_->xp[0][0][0] = 1.0 * m_->x[1][0][0] + m_->dt * m_->x[1][1][0];
        m_->xp[0][1][0] = 0.0 * m_->x[1][0][0] + 1.0 * m_->x[1][1][0];
    }
    m_->z[0][0][0] = m_->zp[0];
    m_->z[0][1][0] = m_->zs[0];
    const double t17_ = m_->z[0][0][0] - (m_->H[0][0] * m_->xp[0][0][0] + m_->H[0][1] * m_->xp[0][1][0]);
    const double t18_ = m_->z[0][1][0] - (m_->H[1][0] * m_->xp[0][0][0] + m_->H[1][1] * m_->xp[0][1][0]);
    m_->x[0][0][0] = m_->index_ == 0 ? 0.0 : m_->xp[0][0][0] + (m_->K[0][0][0] * t17_ + m_->K[0][0][1] * t18_);
    m_->x[0][1][0] = m_->index_ == 0 ? 0.0 : m_->xp[0][1][0] + (m_->K[0][1][0] * t17_ + m_->K[0][1][1] * t18_);
}

#endif
