/* Generated by 'inkamath --compile' from kalman.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. A compiler may also fuse a multiply and an
 * add, rounding once where the definitions round twice (-ffp-contract): often
 * closer to exact, but the step then depends on how it is built, so build
 * what 'inkamath --check' writes the way the step itself is built. */
#ifndef KALMAN_H
#define KALMAN_H

#include <math.h>
#include <string.h>

/* Using it:
 *
 *     kalman m;
 *     kalman_init(&m);
 *     kalman_step(&m, z);  once for each index, the first 0
 *     m.p[0]  is then p_n
 *
 * A step takes z_n, the input at its index. After a step, m.name[k] is
 * name_(n-k) for each sequence: z, Pp, K, P (k <= 1), xp, x (k <= 1) and p.
 * The parameters are fields holding the file's values once kalman_init has
 * run: H (1x2), I (2x2), Q (2x2), R = 1.0 and dt = 1.0. After assigning one,
 * call kalman_update.
 */

/* The parameters, which the host may assign, then what derives from them,
 * then the index of the latest step and each sequence's terms from that
 * index back. */
typedef struct kalman {
    double H[1][2];
    double I[2][2];
    double Q[2][2];
    double R;
    double dt;
    long long index_;
    double z[1];
    double Pp[1][2][2];
    double K[1][2][1];
    double P[2][2][2];
    double xp[1][2][1];
    double x[2][2][1];
    double p[1];
} kalman;

/* Computes what derives from the parameters: call it after assigning one. */
static inline void kalman_update(kalman* m_) {
    (void)m_;
}

static inline void kalman_init(kalman* m_) {
    memset(m_, 0, sizeof *m_);
    m_->H[0][0] = 1.0;
    m_->H[0][1] = 0.0;
    m_->I[0][0] = 1.0;
    m_->I[0][1] = 0.0;
    m_->I[1][0] = 0.0;
    m_->I[1][1] = 1.0;
    m_->Q[0][0] = 0.01;
    m_->Q[0][1] = 0.0;
    m_->Q[1][0] = 0.0;
    m_->Q[1][1] = 0.01;
    m_->R = 1.0;
    m_->dt = 1.0;
    m_->index_ = -1;
    kalman_update(m_);
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void kalman_step(kalman* m_, double z) {
    ++m_->index_;
    memcpy(m_->P[1], m_->P[0], sizeof m_->P[1]);
    memcpy(m_->x[1], m_->x[0], sizeof m_->x[1]);
    m_->z[0] = z;
    if (m_->index_ >= 1) {
        const double t0_ = 1.0 * m_->P[1][0][0] + m_->dt * m_->P[1][1][0];
        const double t1_ = 1.0 * m_->P[1][0][1] + m_->dt * m_->P[1][1][1];
        const double t2_ = 0.0 * m_->P[1][0][0] + 1.0 * m_->P[1][1][0];
        const double t3_ = 0.0 * m_->P[1][0][1] + 1.0 * m_->P[1][1][1];
        m_->Pp[0][0][0] = t0_ * 1.0 + t1_ * m_->dt + m_->Q[0][0];
        m_->Pp[0][0][1] = t0_ * 0.0 + t1_ * 1.0 + m_->Q[0][1];
        m_->Pp[0][1][0] = t2_ * 1.0 + t3_ * m_->dt + m_->Q[1][0];
        m_->Pp[0][1][1] = t2_ * 0.0 + t3_ * 1.0 + m_->Q[1][1];
    }
    if (m_->index_ >= 1) {
        const double t4_ = pow((m_->H[0][0] * m_->Pp[0][0][0] + m_->H[0][1] * m_->Pp[0][1][0]) * m_->H[0][0] + (m_->H[0][0] * m_->Pp[0][0][1] + m_->H[0][1] * m_->Pp[0][1][1]) * m_->H[0][1] + m_->R, -1.0);
        m_->K[0][0][0] = (m_->Pp[0][0][0] * m_->H[0][0] + m_->Pp[0][0][1] * m_->H[0][1]) * t4_;
        m_->K[0][1][0] = (m_->Pp[0][1][0] * m_->H[0][0] + m_->Pp[0][1][1] * m_->H[0][1]) * t4_;
    }
    const double t5_ = m_->I[0][0] + (0.0 - m_->K[0][0][0] * m_->H[0][0]);
    const double t6_ = m_->I[0][1] + (0.0 - m_->K[0][0][0] * m_->H[0][1]);
    const double t7_ = m_->I[1][0] + (0.0 - m_->K[0][1][0] * m_->H[0][0]);
    const double t8_ = m_->I[1][1] + (0.0 - m_->K[0][1][0] * m_->H[0][1]);
    m_->P[0][0][0] = m_->index_ == 0 ? 10.0 : t5_ * m_->Pp[0][0][0] + t6_ * m_->Pp[0][1][0];
    m_->P[0][0][1] = m_->index_ == 0 ? 0.0 : t5_ * m_->Pp[0][0][1] + t6_ * m_->Pp[0][1][1];
    m_->P[0][1][0] = m_->index_ == 0 ? 0.0 : t7_ * m_->Pp[0][0][0] + t8_ * m_->Pp[0][1][0];
    m_->P[0][1][1] = m_->index_ == 0 ? 10.0 : t7_ * m_->Pp[0][0][1] + t8_ * m_->Pp[0][1][1];
    if (m_->index_ >= 1) {
        m_->xp[0][0][0] = 1.0 * m_->x[1][0][0] + m_->dt * m_->x[1][1][0];
        m_->xp[0][1][0] = 0.0 * m_->x[1][0][0] + 1.0 * m_->x[1][1][0];
    }
    const double t9_ = m_->z[0] + (0.0 - (m_->H[0][0] * m_->xp[0][0][0] + m_->H[0][1] * m_->xp[0][1][0]));
    m_->x[0][0][0] = m_->index_ == 0 ? 0.0 : m_->xp[0][0][0] + m_->K[0][0][0] * t9_;
    m_->x[0][1][0] = m_->index_ == 0 ? 0.0 : m_->xp[0][1][0] + m_->K[0][1][0] * t9_;
    m_->p[0] = m_->x[0][0][0];
}

#endif
