/* Generated by 'inkamath --compile' from kernel.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. A compiler may also fuse a multiply and an
 * add, rounding once where the definitions round twice (-ffp-contract): often
 * closer to exact, but the step then depends on how it is built, so build
 * what 'inkamath --check' writes the way the step itself is built. */
#ifndef KERNEL_H
#define KERNEL_H

#include <math.h>
#include <string.h>

/* Using it:
 *
 *     kernel m;
 *     kernel_init(&m);
 *     kernel_step(&m, x);  once for each index, the first 0
 *     m.y[0]  is then y_n
 *
 * A step takes x_n, the input at its index. After a step, m.name[k] is
 * name_(n-k) for each sequence: x, u (k <= 1) and y. The parameters are fields
 * holding the file's values once kernel_init has run: lap (3x3). After
 * assigning one, call kernel_update.
 */

/* The parameters, which the host may assign, then what derives from them,
 * then the index of the latest step and each sequence's terms from that
 * index back. */
typedef struct kernel {
    double lap[3][3];
    long long index_;
    double x[1];
    double u[2][3][3];
    double y[1];
} kernel;

static inline double kernel_ceil(double arg_x) {
    return 0.0 - floor(0.0 - arg_x);
}

/* Computes what derives from the parameters: call it after assigning one. */
static inline void kernel_update(kernel* m_) {
    (void)m_;
}

static inline void kernel_init(kernel* m_) {
    memset(m_, 0, sizeof *m_);
    m_->lap[0][0] = 0.0;
    m_->lap[0][1] = 0.125;
    m_->lap[0][2] = 0.0;
    m_->lap[1][0] = 0.125;
    m_->lap[1][1] = 0.5;
    m_->lap[1][2] = 0.125;
    m_->lap[2][0] = 0.0;
    m_->lap[2][1] = 0.125;
    m_->lap[2][2] = 0.0;
    m_->index_ = -1;
    kernel_update(m_);
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void kernel_step(kernel* m_, double x) {
    ++m_->index_;
    memcpy(m_->u[1], m_->u[0], sizeof m_->u[1]);
    m_->x[0] = x;
    m_->u[0][0][0] = m_->index_ == 0 ? 0.0 : m_->lap[0][0] * 0.0 + m_->lap[0][1] * 0.0 + m_->lap[0][2] * 0.0 + (m_->lap[1][0] * 0.0 + m_->lap[1][1] * m_->u[1][0][0] + m_->lap[1][2] * m_->u[1][0][1]) + (m_->lap[2][0] * 0.0 + m_->lap[2][1] * m_->u[1][1][0] + m_->lap[2][2] * m_->u[1][1][1]);
    m_->u[0][0][1] = m_->index_ == 0 ? 0.0 : m_->lap[0][0] * 0.0 + m_->lap[0][1] * 0.0 + m_->lap[0][2] * 0.0 + (m_->lap[1][0] * m_->u[1][0][0] + m_->lap[1][1] * m_->u[1][0][1] + m_->lap[1][2] * m_->u[1][0][2]) + (m_->lap[2][0] * m_->u[1][1][0] + m_->lap[2][1] * m_->u[1][1][1] + m_->lap[2][2] * m_->u[1][1][2]);
    m_->u[0][0][2] = m_->index_ == 0 ? 0.0 : m_->lap[0][0] * 0.0 + m_->lap[0][1] * 0.0 + m_->lap[0][2] * 0.0 + (m_->lap[1][0] * m_->u[1][0][1] + m_->lap[1][1] * m_->u[1][0][2] + m_->lap[1][2] * 0.0) + (m_->lap[2][0] * m_->u[1][1][1] + m_->lap[2][1] * m_->u[1][1][2] + m_->lap[2][2] * 0.0);
    m_->u[0][1][0] = m_->index_ == 0 ? 0.0 : m_->lap[0][0] * 0.0 + m_->lap[0][1] * m_->u[1][0][0] + m_->lap[0][2] * m_->u[1][0][1] + (m_->lap[1][0] * 0.0 + m_->lap[1][1] * m_->u[1][1][0] + m_->lap[1][2] * m_->u[1][1][1]) + (m_->lap[2][0] * 0.0 + m_->lap[2][1] * m_->u[1][2][0] + m_->lap[2][2] * m_->u[1][2][1]);
    m_->u[0][1][1] = m_->index_ == 0 ? 16.0 : m_->lap[0][0] * m_->u[1][0][0] + m_->lap[0][1] * m_->u[1][0][1] + m_->lap[0][2] * m_->u[1][0][2] + (m_->lap[1][0] * m_->u[1][1][0] + m_->lap[1][1] * m_->u[1][1][1] + m_->lap[1][2] * m_->u[1][1][2]) + (m_->lap[2][0] * m_->u[1][2][0] + m_->lap[2][1] * m_->u[1][2][1] + m_->lap[2][2] * m_->u[1][2][2]);
    m_->u[0][1][2] = m_->index_ == 0 ? 0.0 : m_->lap[0][0] * m_->u[1][0][1] + m_->lap[0][1] * m_->u[1][0][2] + m_->lap[0][2] * 0.0 + (m_->lap[1][0] * m_->u[1][1][1] + m_->lap[1][1] * m_->u[1][1][2] + m_->lap[1][2] * 0.0) + (m_->lap[2][0] * m_->u[1][2][1] + m_->lap[2][1] * m_->u[1][2][2] + m_->lap[2][2] * 0.0);
    m_->u[0][2][0] = m_->index_ == 0 ? 0.0 : m_->lap[0][0] * 0.0 + m_->lap[0][1] * m_->u[1][1][0] + m_->lap[0][2] * m_->u[1][1][1] + (m_->lap[1][0] * 0.0 + m_->lap[1][1] * m_->u[1][2][0] + m_->lap[1][2] * m_->u[1][2][1]) + (m_->lap[2][0] * 0.0 + m_->lap[2][1] * 0.0 + m_->lap[2][2] * 0.0);
    m_->u[0][2][1] = m_->index_ == 0 ? 0.0 : m_->lap[0][0] * m_->u[1][1][0] + m_->lap[0][1] * m_->u[1][1][1] + m_->lap[0][2] * m_->u[1][1][2] + (m_->lap[1][0] * m_->u[1][2][0] + m_->lap[1][1] * m_->u[1][2][1] + m_->lap[1][2] * m_->u[1][2][2]) + (m_->lap[2][0] * 0.0 + m_->lap[2][1] * 0.0 + m_->lap[2][2] * 0.0);
    m_->u[0][2][2] = m_->index_ == 0 ? 0.0 : m_->lap[0][0] * m_->u[1][1][1] + m_->lap[0][1] * m_->u[1][1][2] + m_->lap[0][2] * 0.0 + (m_->lap[1][0] * m_->u[1][2][1] + m_->lap[1][1] * m_->u[1][2][2] + m_->lap[1][2] * 0.0) + (m_->lap[2][0] * 0.0 + m_->lap[2][1] * 0.0 + m_->lap[2][2] * 0.0);
    m_->y[0] = (m_->x[0] - 0.5 < 0.0 ? 0.0 : m_->x[0] - 0.5) + 32.0 + kernel_ceil(m_->x[0]);
}

#endif
