/* Generated by 'inkamath --compile' from loop.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. A compiler may also fuse a multiply and an
 * add, rounding once where the definitions round twice (-ffp-contract): often
 * closer to exact, but the step then depends on how it is built, so build
 * what 'inkamath --check' writes the way the step itself is built. */
#ifndef LOOP_H
#define LOOP_H

#include <math.h>
#include <string.h>

/* Using it:
 *
 *     loop m;
 *     loop_init(&m);
 *     loop_step(&m);  once for each index, the first 0
 *     m.plt.u[0]  is then plt.u_n
 *
 * A step takes no input. After a step, m.name[k] is name_(n-k) for each
 * sequence: plt.x (k <= 1), ctl.y, ctl.u and plt.u (k <= 1). The parameters
 * are fields holding the file's values once loop_init has run: ctl.kp = 2.0,
 * ctl.r = 1.0 and plt.dt = 0.5. After assigning one, call loop_update.
 */

/* The parameters, which the host may assign, then what derives from them,
 * then the index of the latest step and each sequence's terms from that
 * index back. */
typedef struct loop {
    long long index_;
    struct {
        double kp;
        double r;
        double y[1];
        double u[1];
    } ctl;
    struct {
        double dt;
        double x[2];
        double u[2];
    } plt;
} loop;

/* Computes what derives from the parameters: call it after assigning one. */
static inline void loop_update(loop* m_) {
    (void)m_;
}

static inline void loop_init(loop* m_) {
    memset(m_, 0, sizeof *m_);
    m_->ctl.kp = 2.0;
    m_->ctl.r = 1.0;
    m_->plt.dt = 0.5;
    m_->index_ = -1;
    loop_update(m_);
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void loop_step(loop* m_) {
    ++m_->index_;
    m_->plt.x[1] = m_->plt.x[0];
    m_->plt.u[1] = m_->plt.u[0];
    m_->plt.x[0] = m_->index_ == 0 ? 0.0 : m_->plt.x[1] + m_->plt.dt * (m_->plt.u[1] - m_->plt.x[1]);
    m_->ctl.y[0] = m_->plt.x[0];
    m_->ctl.u[0] = m_->ctl.kp * (m_->ctl.r - m_->ctl.y[0]);
    m_->plt.u[0] = m_->ctl.u[0];
}

#endif
