/* Generated by 'inkamath --compile' from mix in mix.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. A compiler may also fuse a multiply and an
 * add, rounding once where the definitions round twice (-ffp-contract): often
 * closer to exact, but the step then depends on how it is built, so build
 * what 'inkamath --check' writes the way the step itself is built. */
#ifndef MIX_H
#define MIX_H

#include <math.h>
#include <string.h>

/* Using it:
 *
 *     mix m;
 *     mix_init(&m);
 *     mix_step(&m, u, b);  once for each index, the first 0
 *     m.v[0]  is then v_n
 *
 * A step takes u_n and b_n, the inputs at its index. After a step, m.name[k]
 * is name_(n-k) for each sequence: u, b, m and v (k <= 1). The parameters are
 * fields holding the model's defaults once mix_init has run: a = 0.25 and
 * g = 0.5. After assigning one, call mix_update.
 */

/* The parameters, which the host may assign, then what derives from them,
 * then the index of the latest step and each sequence's terms from that
 * index back. */
typedef struct mix {
    double a;
    double g;
    long long index_;
    double u[1];
    double b[1];
    double m[1];
    double v[2];
} mix;

/* Computes what derives from the parameters: call it after assigning one. */
static inline void mix_update(mix* m_) {
    (void)m_;
}

static inline void mix_init(mix* m_) {
    memset(m_, 0, sizeof *m_);
    m_->a = 0.25;
    m_->g = 0.5;
    m_->index_ = -1;
    mix_update(m_);
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void mix_step(mix* m_, double u, double b) {
    ++m_->index_;
    m_->v[1] = m_->v[0];
    m_->u[0] = u;
    m_->b[0] = b;
    m_->m[0] = m_->g * m_->u[0] + (1.0 + (0.0 - m_->g)) * m_->b[0];
    m_->v[0] = m_->index_ == 0 ? 0.0 : m_->a * m_->m[0] + (1.0 + (0.0 - m_->a)) * m_->v[1];
}

#endif
