/* Generated by 'inkamath --compile' from net.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. */
#ifndef NET_H
#define NET_H

#include <math.h>
#include <string.h>

/* Using it:
 *
 *     net m;
 *     net_init(&m);
 *     net_step(&m, x);  once for each index, the first 0
 *     m.y[0]  is then y_n
 *
 * A step takes x_n, the input at its index. After a step, m.name[k] is
 * name_(n-k) for each sequence: x, w (k <= 1), z, h and y. The parameters are
 * fields holding the file's values once net_init has run: W (2x3) and v (1x2).
 * After assigning one, call net_update.
 */

/* The parameters, which the host may assign, then what derives from them,
 * then the index of the latest step and each sequence's terms from that
 * index back. */
typedef struct net {
    double W[2][3];
    double v[1][2];
    long long index_;
    double x[1];
    double w[2][3][1];
    double z[1][2][1];
    double h[1][2][1];
    double y[1];
} net;

/* Computes what derives from the parameters: call it after assigning one. */
static inline void net_update(net* m_) {
    (void)m_;
}

static inline void net_init(net* m_) {
    memset(m_, 0, sizeof *m_);
    m_->W[0][0] = 0.5;
    m_->W[0][1] = -0.25;
    m_->W[0][2] = 0.25;
    m_->W[1][0] = -0.5;
    m_->W[1][1] = 1.0;
    m_->W[1][2] = 0.5;
    m_->v[0][0] = 1.0;
    m_->v[0][1] = -0.5;
    m_->index_ = -1;
    net_update(m_);
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void net_step(net* m_, double x) {
    ++m_->index_;
    memcpy(m_->w[1], m_->w[0], sizeof m_->w[1]);
    m_->x[0] = x;
    m_->w[0][0][0] = m_->index_ == 0 ? 0.0 : m_->x[0];
    m_->w[0][1][0] = m_->index_ == 0 ? 0.0 : m_->w[1][0][0];
    m_->w[0][2][0] = m_->index_ == 0 ? 0.0 : m_->w[1][1][0];
    m_->z[0][0][0] = m_->W[0][0] * m_->w[0][0][0] + m_->W[0][1] * m_->w[0][1][0] + m_->W[0][2] * m_->w[0][2][0];
    m_->z[0][1][0] = m_->W[1][0] * m_->w[0][0][0] + m_->W[1][1] * m_->w[0][1][0] + m_->W[1][2] * m_->w[0][2][0];
    m_->h[0][0][0] = m_->z[0][0][0] < 0.0 ? 0.0 : m_->z[0][0][0];
    m_->h[0][1][0] = m_->z[0][1][0] < 0.0 ? 0.0 : m_->z[0][1][0];
    m_->y[0] = m_->v[0][0] * m_->h[0][0][0] + m_->v[0][1] * m_->h[0][1][0];
}

#endif
