/* Generated by 'inkamath --compile' from pid.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. */
#ifndef PID_H
#define PID_H

#include <math.h>
#include <string.h>

/* Using it:
 *
 *     pid m;
 *     pid_init(&m);
 *     pid_step(&m, y);  once for each index, the first 0
 *     m.u[0]  is then u_n
 *
 * A step takes y_n, the input at its index. After a step, m.name[k] is
 * name_(n-k) for each sequence: y, e (k <= 1), d, s (k <= 1) and u. The
 * parameters are fields holding the file's values once pid_init has run: dt =
 * 0.1, kd = 0.1, ki = 1.0, kp = 2.0 and r = 1.0. After assigning one, call
 * pid_update.
 */

/* The parameters, which the host may assign, then what derives from them,
 * then the index of the latest step and each sequence's terms from that
 * index back. */
typedef struct pid {
    double dt;
    double kd;
    double ki;
    double kp;
    double r;
    long long index_;
    double y[1];
    double e[2];
    double d[1];
    double s[2];
    double u[1];
} pid;

/* Computes what derives from the parameters: call it after assigning one. */
static inline void pid_update(pid* m_) {
    (void)m_;
}

static inline void pid_init(pid* m_) {
    memset(m_, 0, sizeof *m_);
    m_->dt = 0.1;
    m_->kd = 0.1;
    m_->ki = 1.0;
    m_->kp = 2.0;
    m_->r = 1.0;
    m_->index_ = -1;
    pid_update(m_);
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void pid_step(pid* m_, double y) {
    ++m_->index_;
    m_->e[1] = m_->e[0];
    m_->s[1] = m_->s[0];
    m_->y[0] = y;
    m_->e[0] = m_->r - m_->y[0];
    m_->d[0] = m_->index_ == 0 ? 0.0 : (m_->e[0] - m_->e[1]) / m_->dt;
    m_->s[0] = m_->index_ == 0 ? 0.0 : m_->s[1] + m_->e[0] * m_->dt;
    m_->u[0] = m_->kp * m_->e[0] + m_->ki * m_->s[0] + m_->kd * m_->d[0];
}

#endif
