/* Generated by 'inkamath --compile' from pid_clamped.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. */
#ifndef PID_CLAMPED_H
#define PID_CLAMPED_H

#include <math.h>
#include <string.h>

/* The parameters, which the host may assign, then what derives from them,
 * then the index of the latest step and each sequence's terms from that
 * index back. */
typedef struct pid_clamped {
    double dt;
    double kd;
    double ki;
    double kp;
    double r;
    double umax;
    long long index_;
    double y[1];
    double e[2];
    double d[1];
    double s[2];
    double v[1];
    double u[2];
} pid_clamped;

/* Computes what derives from the parameters: call it after assigning one. */
static inline void pid_clamped_update(pid_clamped* m_) {
    (void)m_;
}

static inline void pid_clamped_init(pid_clamped* m_) {
    memset(m_, 0, sizeof *m_);
    m_->dt = 0.1;
    m_->kd = 0.1;
    m_->ki = 1.0;
    m_->kp = 2.0;
    m_->r = 1.0;
    m_->umax = 1.5;
    m_->index_ = -1;
    pid_clamped_update(m_);
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void pid_clamped_step(pid_clamped* m_, double y) {
    ++m_->index_;
    m_->e[1] = m_->e[0];
    m_->s[1] = m_->s[0];
    m_->u[1] = m_->u[0];
    m_->y[0] = y;
    m_->e[0] = m_->r - m_->y[0];
    m_->d[0] = m_->index_ == 0 ? 0.0 : (m_->e[0] - m_->e[1]) / m_->dt;
    m_->s[0] = m_->index_ == 0 ? 0.0 : m_->u[1] >= m_->umax ? m_->s[1] : m_->u[1] <= -m_->umax ? m_->s[1] : m_->s[1] + m_->e[0] * m_->dt;
    m_->v[0] = m_->kp * m_->e[0] + m_->ki * m_->s[0] + m_->kd * m_->d[0];
    m_->u[0] = m_->v[0] > m_->umax ? m_->umax : m_->v[0] < -m_->umax ? -m_->umax : m_->v[0];
}

#endif
