/* Generated by 'inkamath --compile --float' from adc.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. A compiler may also fuse a multiply and an
 * add, rounding once where the definitions round twice (-ffp-contract): often
 * closer to exact, but the step then depends on how it is built, so build
 * what 'inkamath --check' writes the way the step itself is built. */
#ifndef ADC_H
#define ADC_H

#include <math.h>
#include <string.h>

/* Using it:
 *
 *     adc m;
 *     adc_init(&m);
 *     adc_step(&m, x);  once for each index, the first 0
 *     m.rising[0]  is then rising_n
 *
 * A step takes x_n, the input at its index. After a step, m.name[k] is
 * name_(n-k) for each sequence: x, v, held (k <= 1), alarm and rising. The
 * parameters are fields holding the file's values once adc_init has run:
 * hi = 1.0f, lo = -1.0f and q = 0.25f. After assigning one, call adc_update.
 * Every value is a float, and every operation rounds to one. A term the
 * interpreter would refuse is NaN, and so is every term that reads one,
 * through a guard or a comparison as through arithmetic. Built with
 * -ffinite-math-only, which -ffast-math implies, GCC removes the tests that
 * make it so, and Clang warns of each NaN.
 */

/* The parameters, which the host may assign, then what derives from them,
 * then the index of the latest step and each sequence's terms from that
 * index back. */
typedef struct adc {
    float hi;
    float lo;
    float q;
    long long index_;
    float x[1];
    float v[1];
    float held[2];
    float alarm[1];
    float rising[1];
} adc;

/* Computes what derives from the parameters: call it after assigning one. */
static inline void adc_update(adc* m_) {
    (void)m_;
}

static inline void adc_init(adc* m_) {
    memset(m_, 0, sizeof *m_);
    m_->hi = 1.0f;
    m_->lo = -1.0f;
    m_->q = 0.25f;
    m_->index_ = -1;
    adc_update(m_);
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void adc_step(adc* m_, float x) {
    ++m_->index_;
    m_->held[1] = m_->held[0];
    m_->x[0] = x;
    m_->v[0] = m_->q * floorf(m_->x[0] / m_->q);
    const float t1_ = (isnan(m_->held[1] + (0.0f - m_->v[0])) || isnan(m_->q) ? NAN : m_->held[1] + (0.0f - m_->v[0]) < m_->q ? 1.0f : 0.0f);
    const float t2_ = (t1_ == 0.0f ? 0.0f : t1_ != t1_ ? NAN : (isnan(m_->v[0] + (0.0f - m_->held[1])) || isnan(m_->q) ? NAN : m_->v[0] + (0.0f - m_->held[1]) < m_->q ? 1.0f : 0.0f));
    m_->held[0] = m_->index_ == 0 ? 0.0f : isnan(t2_) ? NAN : t2_ != 0.0f ? m_->held[1] : m_->v[0];
    const float t0_ = (isnan(m_->held[0]) || isnan(m_->lo) ? NAN : m_->held[0] < m_->lo ? 1.0f : 0.0f);
    m_->alarm[0] = (t0_ == 0.0f ? (isnan(m_->held[0]) || isnan(m_->hi) ? NAN : m_->held[0] > m_->hi ? 1.0f : 0.0f) : t0_ != t0_ ? NAN : 1.0f);
    const float t3_ = ((float)m_->index_ > 0.0f ? 1.0f : 0.0f);
    m_->rising[0] = (t3_ == 0.0f ? 0.0f : t3_ != t3_ ? NAN : (m_->index_ < 1 ? NAN : (isnan(m_->held[0]) || isnan(m_->held[1]) ? NAN : m_->held[0] > m_->held[1] ? 1.0f : 0.0f)));
}

#endif
