/* Generated by 'inkamath --compile --float' from pid.ink: edit that, not this.
 * The arithmetic is in the order the definitions give it, so do not build it
 * with -ffast-math, which reorders. A compiler may also fuse a multiply and an
 * add, rounding once where the definitions round twice (-ffp-contract): often
 * closer to exact, but the step then depends on how it is built, so build
 * what 'inkamath --check' writes the way the step itself is built. */
#ifndef PID_H
#define PID_H

#include <math.h>
#include <string.h>

/* Using it:
 *
 *     pid m;
 *     pid_init(&m);
 *     pid_step(&m, y);  once for each index, the first 0
 *     m.u[0]  is then u_n
 *
 * A step takes y_n, the input at its index. After a step, m.name[k] is
 * name_(n-k) for each sequence: y, e (k <= 1), d, s (k <= 1) and u. The
 * parameters are fields holding the file's values once pid_init has run:
 * dt = 0.1f, kd = 0.1f, ki = 1.0f, kp = 2.0f and r = 1.0f. After assigning
 * one, call pid_update. Every value is a float, and every operation rounds to
 * one.
 */

/* The parameters, which the host may assign, then what derives from them,
 * then the index of the latest step and each sequence's terms from that
 * index back. */
typedef struct pid {
    float dt;
    float kd;
    float ki;
    float kp;
    float r;
    long long index_;
    float y[1];
    float e[2];
    float d[1];
    float s[2];
    float u[1];
} pid;

/* Computes what derives from the parameters: call it after assigning one. */
static inline void pid_update(pid* m_) {
    (void)m_;
}

static inline void pid_init(pid* m_) {
    memset(m_, 0, sizeof *m_);
    m_->dt = 0.1f;
    m_->kd = 0.1f;
    m_->ki = 1.0f;
    m_->kp = 2.0f;
    m_->r = 1.0f;
    m_->index_ = -1;
    pid_update(m_);
}

/* Advances to the next index, the first at 0, and computes its terms. */
static inline void pid_step(pid* m_, float y) {
    ++m_->index_;
    m_->e[1] = m_->e[0];
    m_->s[1] = m_->s[0];
    m_->y[0] = y;
    m_->e[0] = m_->r + (0.0f - m_->y[0]);
    m_->d[0] = m_->index_ == 0 ? 0.0f : (m_->e[0] + (0.0f - m_->e[1])) / m_->dt;
    m_->s[0] = m_->index_ == 0 ? 0.0f : m_->s[1] + m_->e[0] * m_->dt;
    m_->u[0] = m_->kp * m_->e[0] + m_->ki * m_->s[0] + m_->kd * m_->d[0];
}

#endif
